# Generated by Django 2.2.26 on 2022-03-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('pinned', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('biography', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Forum')),
                ('user', models.ManyToManyField(to='collab_app.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('text', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab_app.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab_app.Page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCategoryAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Forum')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Forum'),
        ),
    ]
