# Generated by Django 2.2.26 on 2022-03-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab_app.UserProfile'),
        ),
        migrations.CreateModel(
            name='ForumCategoryAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Category')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab_app.Forum')),
            ],
        ),
    ]
