# Generated by Django 2.2.26 on 2022-03-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0002_auto_20220321_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='forum',
        ),
    ]
